language: php

php:
#  - 5.3
#  - 5.4
#  - 5.5
  - 5.6
#  - nightly

#env:
#  - DB=mysql
#  - DB=pgsql

before_script:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar

script:
  - php php-cs-fixer.phar fix --config-file=".php_cs" --verbose --dry-run
